# TTS Service Configuration

[server]
bind_addr = "[::1]:3000"
workers = 4              # Number of worker threads, 0 = number of CPU cores

[server.cors]
enabled = true
allow_origins = ["*"]
allow_methods = ["GET", "POST"]
allow_headers = ["Content-Type", "Authorization"]

[models]
snac_decoder_path = "./models/snac_decoder.onnx"
cache_models = true                              # Keep models loaded in memory

[token_generator]
api_url = "http://127.0.0.1:1234/v1/completions"
model = "legraphista/Orpheus"
temperature = 0.7
stop_sequence = "<|begin_of_text|>"
timeout_secs = 30
retry_attempts = 3

[audio]
sample_rate = 24000
channels = 1
bits_per_sample = 16
# Audio processing settings
context_frames = 4
audio_slice_start = 2048
audio_slice_end = 4096

[streaming]
channel_buffer_size = 100
chunk_size = 2048         # Bytes per audio chunk

[logging]
level = "info"                  # trace, debug, info, warn, error
format = "pretty"               # pretty, json, compact
file = "./logs/tts-service.log" # Optional log file
rotation = "daily"              # daily, size, never

[api]
max_request_size = "10MB"
request_timeout_secs = 300

[api.rate_limiting]
enabled = true
requests_per_minute = 60
burst_size = 10

# Voice-specific configurations
[voices.coral]
description = "Warm, friendly female voice"
custom_temperature = 0.8

[voices.sage]
description = "Clear, professional male voice"
custom_temperature = 0.6
