[server]
bind_addr = "[::1]:3000"

[server.cors]
enabled = true
allow_origins = ["*"]
allow_methods = ["GET", "POST"]
allow_headers = ["Content-Type", "Authorization"]

[audio]
snac_decoder_path = "./models/snac_decoder.onnx"

[streaming]
channel_buffer_size = 100

[logging]
level = "info"    # trace, debug, info, warn, error
format = "pretty" # pretty, json, compact

[api]
max_request_size = "10MB"
request_timeout_secs = 300
default_model = "orpheus-en" # Default model if not specified in request

# Token generator providers
[providers.local-lm-studio]
api_url = "http://localhost:1234/v1/completions"
api_key = "dummy-api-key"                        # Optional, empty for local servers
timeout_secs = 30
retry_attempts = 3
concurrent_requests = 1

[providers.ollama]
api_url = "http://localhost:11434/api/generate"
api_key = "dummy-api-key"
timeout_secs = 30
retry_attempts = 3
concurrent_requests = 1
