# Hindi Model
[models.orpheus-hi]
provider = "local-lm-studio"
id = "lex-au/Orpheus-3b-Hindi-FT-Q8_0.gguf"
temperature = 0.6
top_p = 0.8
repetition_penalty = 1.3
max_context_length = 8192
stop_sequence = "<|begin_of_text|>"
description = "Orpheus 3B Hindi TTS model"

[models.orpheus-hi.voices."ऋतिका"]
description = "Female, expressive"
languages = ["hi"]
