# Italian & Spanish Model
[models.orpheus-it-es]
provider = "local-lm-studio"
id = "lex-au/Orpheus-3b-Italian_Spanish-FT-Q8_0.gguf"
temperature = 0.6
top_p = 0.8
repetition_penalty = 1.3
max_context_length = 8192
stop_sequence = "<|begin_of_text|>"
description = "Orpheus 3B Italian & Spanish TTS model"

# Italian voices
[models.orpheus-it-es.voices.pietro]
description = "Male, passionate"
languages = ["it"]

[models.orpheus-it-es.voices.giulia]
description = "Female, expressive"
languages = ["it"]

[models.orpheus-it-es.voices.carlo]
description = "Male, refined"
languages = ["it"]

# Spanish voices
[models.orpheus-it-es.voices.javi]
description = "Male, warm"
languages = ["es"]

[models.orpheus-it-es.voices.sergio]
description = "Male, professional"
languages = ["es"]

[models.orpheus-it-es.voices.maria]
description = "Female, friendly"
languages = ["es"]
